-- Generated by Oracle SQL Developer Data Modeler 4.0.3.853
--   at:        2015-04-22 20:31:31 BST
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c




CREATE TABLE Booking
  (
    Cruise_ID    VARCHAR2 (8) NOT NULL ,
    Voyage_ID    VARCHAR2 (7) NOT NULL ,
    Passenger_No VARCHAR2 (7) NOT NULL ,
    BCabNo       NUMBER (6) NOT NULL ,
    BClass       VARCHAR2 (10) NOT NULL ,
    BEval        NUMBER (1)
  ) ;
ALTER TABLE Booking ADD CHECK ( BClass IN ('First', 'Second', 'Third')) ;
ALTER TABLE Booking ADD CHECK ( BEval  IN (0, 1, 2, 3, 4)) ;
ALTER TABLE Booking ADD CONSTRAINT Booking_PK PRIMARY KEY ( Voyage_ID, Passenger_No, Cruise_ID ) ;

CREATE TABLE Cruise
  (
    Cruise_ID VARCHAR2 (8) NOT NULL ,
    CName     VARCHAR2 (20) NOT NULL ,
    CDuration NUMBER (1) NOT NULL
  ) ;
ALTER TABLE Cruise ADD CHECK ( CDuration IN (2, 3, 4, 5)) ;
ALTER TABLE Cruise ADD CONSTRAINT Cruise_PK PRIMARY KEY ( Cruise_ID ) ;

CREATE TABLE Passenger
  (
    Passenger_No VARCHAR2 (7) NOT NULL ,
    PFName       VARCHAR2 (10) NOT NULL ,
    PSName       VARCHAR2 (10) NOT NULL ,
    PAddress     VARCHAR2 (20) NOT NULL ,
    PGender      VARCHAR2 (10) NOT NULL ,
    PTelNo       NUMBER (12) NOT NULL ,
    PEmail       VARCHAR2 (30)
  ) ;
ALTER TABLE Passenger ADD CONSTRAINT Passenger_PK PRIMARY KEY ( Passenger_No ) ;

CREATE TABLE Ship
  (
    S_No     VARCHAR2 (6) NOT NULL ,
    SName    VARCHAR2 (20) NOT NULL ,
    SPort    VARCHAR2 (10) NOT NULL ,
    STonnage NUMBER (5) NOT NULL
  ) ;
ALTER TABLE Ship ADD CHECK ( STonnage BETWEEN 25000 AND 60000) ;
ALTER TABLE Ship ADD CONSTRAINT Ship_PK PRIMARY KEY ( S_No ) ;

CREATE TABLE Voyage
  (
    Voyage_ID VARCHAR2 (7) NOT NULL ,
    VName     VARCHAR2 (20) NOT NULL ,
    VDate     DATE NOT NULL ,
    VSloc     VARCHAR2 (10) NOT NULL ,
    VCost     NUMBER (4) NOT NULL ,
    S_No      VARCHAR2 (6) NOT NULL ,
    Cruise_ID VARCHAR2 (8) NOT NULL
  ) ;
ALTER TABLE Voyage ADD CHECK ( VSloc IN ('Athens', 'Naples', 'Nice', 'Rome')) ;
ALTER TABLE Voyage ADD CHECK ( VCost BETWEEN 600 AND 5000) ;
ALTER TABLE Voyage ADD CONSTRAINT Voyage_PK PRIMARY KEY ( Voyage_ID ) ;

ALTER TABLE Booking ADD CONSTRAINT Booking_Cruise_FK FOREIGN KEY ( Cruise_ID ) REFERENCES Cruise ( Cruise_ID ) ;

ALTER TABLE Booking ADD CONSTRAINT Booking_Passenger_FK FOREIGN KEY ( Passenger_No ) REFERENCES Passenger ( Passenger_No ) ;

ALTER TABLE Booking ADD CONSTRAINT Booking_Voyage_FK FOREIGN KEY ( Voyage_ID ) REFERENCES Voyage ( Voyage_ID ) ;

ALTER TABLE Voyage ADD CONSTRAINT Voyage_Cruise_FK FOREIGN KEY ( Cruise_ID ) REFERENCES Cruise ( Cruise_ID ) ;

ALTER TABLE Voyage ADD CONSTRAINT Voyage_Ship_FK FOREIGN KEY ( S_No ) REFERENCES Ship ( S_No ) ;


-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             5
-- CREATE INDEX                             0
-- ALTER TABLE                             16
-- CREATE VIEW                              0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
